package com.dcc.app.data

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The seed dynasty, generated by scripts/generate-data.mjs and shipped as an
 * asset. The desktop app reads the identical file, so both apps show the same
 * universe.
 */
@Serializable
data class Dynasty(
    val meta: Meta,
    val teams: List<Team>,
    val players: List<Player>,
    val prospects: List<Prospect>,
    val schedule: List<Game>,
    val stories: List<Story>,
    val coach: Coach,
    val national: National,
    val devices: Devices,
    val seededBoard: List<String>,
)

@Serializable
data class Meta(
    val season: Int,
    val currentWeek: Int,
    val userTeamId: String,
    val rosterLimit: Int,
)

@Serializable
data class Team(
    val id: String,
    val name: String,
    val abbr: String,
    val monogram: String,
    val conference: String,
    val pipeline: String,
    val isUser: Boolean,
    val tone: Int,
    val rank: Int,
    val wins: Int,
    val losses: Int,
    val prestige: Int,
    val trend: String,
)

@Serializable
data class Player(
    val id: String,
    val name: String,
    val teamId: String,
    val pos: String,
    val ovr: Int,
    val depth: Int,
    val year: String,
    val dev: String,
    val archetype: String,
    val height: String,
    val weight: Int,
    val redshirt: Boolean,
    val hometown: String,
    val dealbreaker: String,
    val nil: Int,
)

@Serializable
data class Prospect(
    val id: String,
    val name: String,
    val pos: String,
    val stars: Int,
    val natlRank: Int,
    val posRank: Int,
    val stateRank: Int,
    val ovr: Int,
    val ovrRevealed: Boolean,
    val archetype: String,
    val height: String,
    val weight: Int,
    val town: String,
    val state: String,
    val pipeline: String,
    val stage: String,
    val commitPoints: Int,
    val nil: Int,
    val topSchools: List<String>,
    val watchlist: Boolean,
)

@Serializable
data class Game(
    val id: String,
    val teamId: String,
    val week: Int,
    val opponentId: String,
    val home: Boolean,
    val ranked: Boolean,
    val rivalry: Boolean,
    val kickoff: String,
    val result: String? = null,
    val score: String? = null,
    val storyId: String? = null,
)

@Serializable
data class StoryEffect(val label: String, val targets: List<EffectTarget> = emptyList())

@Serializable
data class EffectTarget(val playerId: String, val stat: String, val delta: Int)

@Serializable
data class Story(
    val id: String,
    val kicker: String,
    val week: Int,
    val time: String,
    val headline: String,
    val body: String,
    val effect: StoryEffect? = null,
    val status: String = "open",
    val media: List<String> = emptyList(),
)

@Serializable
data class Coach(
    val name: String,
    val record: Record,
    val titles: Int,
    val drafted: Int,
    val timeline: List<TimelineEntry>,
    val draftPicks: List<DraftPick>,
    val honors: List<Honor>,
)

@Serializable
data class Record(val wins: Int, val losses: Int)

@Serializable
data class TimelineEntry(val school: String, val years: String, val record: String, val note: String)

@Serializable
data class DraftPick(val name: String, val pos: String, val round: Int, val year: Int, val team: String)

@Serializable
data class Honor(val tag: String, val text: String)

@Serializable
data class National(val leaders: List<LeaderCategory>, val scores: List<Score>)

@Serializable
data class LeaderCategory(val cat: String, val rows: List<LeaderRow>)

@Serializable
data class LeaderRow(val name: String, val team: String, val value: String)

@Serializable
data class Score(val home: String, val away: String, val score: String? = null, val final: Boolean)

@Serializable
data class Devices(val holder: String, val machines: List<Machine>, val history: List<SaveVersion>)

@Serializable
data class Machine(
    val id: String,
    val name: String,
    val role: String,
    val hash: String,
    val lastUpload: String,
    val online: Boolean,
)

@Serializable
data class SaveVersion(val version: String, val `when`: String, val size: String, val machine: String)

// ── mutable app state ────────────────────────────────────────────────────────

@Serializable
data class QueueItem(
    val id: String,
    val type: String,
    val title: String,
    val detail: String,
    val state: String = "HELD",
    val origin: String = "android",
    val at: Long,
    val needsConfirm: Boolean = false,
    @SerialName("applyKind") val applyKind: String = "noop",
    val applyPlayerId: String? = null,
    val applyOvr: Int? = null,
    val applyProspectId: String? = null,
    val applyStage: String? = null,
    val applyTeamId: String? = null,
    val applyPos: String? = null,
    val applyOrder: List<String> = emptyList(),
)

@Serializable
data class ChatMessage(val from: String, val text: String, val at: Long)

@Serializable
data class Convo(
    val playerId: String,
    val messages: List<ChatMessage> = emptyList(),
    val interest: Int = 0,
    val status: String = "open",
    val role: String = "Rotational",
    val promises: List<String> = emptyList(),
    val nilOffer: Int = 0,
    val contacted: Boolean = false,
)

@Serializable
data class LogLine(val at: Long, val text: String, val kind: String = "info")

@Serializable
data class PlayerPatch(
    val ovr: Int? = null,
    val dev: String? = null,
    val year: String? = null,
    val pos: String? = null,
    val redshirt: Boolean? = null,
)

@Serializable
data class ProspectPatch(
    val stage: String? = null,
    val ovrRevealed: Boolean? = null,
    val topSchools: List<String>? = null,
)

/** Everything the user changes. Written to filesDir so it survives an update. */
@Serializable
data class Persisted(
    /**
     * Where the loaded dynasty came from: "none" until one is imported, or
     * "sample" for the bundled demo. The app shows nothing real until a save
     * has actually been brought in from the PC.
     */
    val dynastySource: String = "none",
    val theme: String = "gold",
    /** Gold Standard only: which of its two modes, and the accent it derives from. */
    val mode: String = "dark",
    val accent: String = "#D4AF5A",
    val week: Int = 1,
    val heat: Int = 0,
    val gameRunning: Boolean = true,
    val leaseHolder: String = "gaming-pc",
    /**
     * The desktop app's own server on the home network, e.g.
     * http://192.168.1.42:7327, with the code it prints beside it. Both are
     * read off the desktop screen, and the code is made fresh every time that
     * server is switched on.
     */
    val relayUrl: String = "",
    val relayToken: String = "",
    /**
     * Where the desktop publishes for the times the phone is not at home:
     * "owner/name" of a repository the user owns, and a token with repo access
     * to it. A secret, so it is shown as one and never written to the log.
     */
    val githubRepo: String = "",
    val githubToken: String = "",
    /**
     * Which route last brought a snapshot in — "file", "wifi" or "github", and
     * empty until one has. Remembered so a refresh is one tap with nothing to
     * type again.
     */
    val snapshotSource: String = "",
    /**
     * The recruits whose overall the user has chosen to see. The game keeps it
     * hidden until a recruit is scouted, so the app does too rather than handing
     * over a mechanic the dynasty is built on. Keyed by the save's own player
     * id, so fetching the snapshot again does not move the reveals onto other
     * players.
     */
    val revealedRecruits: List<Int> = emptyList(),
    /** Every overall at once, for a user who does not want the mechanic. */
    val revealAllRecruits: Boolean = false,
    val queue: List<QueueItem> = emptyList(),
    val storyStatus: Map<String, String> = emptyMap(),
    val board: List<String> = emptyList(),
    val playerOverrides: Map<String, PlayerPatch> = emptyMap(),
    val prospectOverrides: Map<String, ProspectPatch> = emptyMap(),
    val depthOverrides: Map<String, List<String>> = emptyMap(),
    val convos: Map<String, Convo> = emptyMap(),
    val extraStories: List<Story> = emptyList(),
    val log: List<LogLine> = emptyList(),
)
