#!/usr/bin/env node
/**
 * Propagates the version in the root package.json to every build that needs it.
 *
 * The root package.json is the single source of truth. Android additionally
 * needs an integer versionCode: it is derived from semver so it always
 * increases, which is what lets a new APK install over the old one instead of
 * being rejected as a downgrade.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const read = (p) => JSON.parse(readFileSync(resolve(root, p), 'utf8'))

const { version } = read('package.json')
const m = /^(\d+)\.(\d+)\.(\d+)$/.exec(version)
if (!m) throw new Error(`root package.json version "${version}" is not plain semver (x.y.z)`)
const [, major, minor, patch] = m.map(Number)
if (minor > 99 || patch > 99) throw new Error(`minor/patch must stay under 100 to keep versionCode monotonic (got ${version})`)
const versionCode = major * 10000 + minor * 100 + patch

const desktopPath = resolve(root, 'apps/desktop/package.json')
const desktop = read('apps/desktop/package.json')
if (desktop.version !== version) {
  desktop.version = version
  writeFileSync(desktopPath, JSON.stringify(desktop, null, 2) + '\n')
}

writeFileSync(
  resolve(root, 'apps/android/version.properties'),
  `# Generated by scripts/sync-version.mjs — edit the version in the root package.json instead.\n` +
    `dccVersionName=${version}\ndccVersionCode=${versionCode}\n`,
)

console.log(`version ${version} · android versionCode ${versionCode}`)
